export default {
  LOGIN: "LOGIN",
  SAVE_TOKEN_SUCCESS: 'SAVE_TOKEN_SUCCESS',
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  GET_USER_ADMIN_ROLE: "GET_USER_ADMIN_ROLE",
}
