export default {
  GET_ORGANIZATIONS: 'GET_ORGANIZATIONS',
  GET_ORGANIZATIONS_SUCCESS: 'GET_ORGANIZATIONS_SUCCESS',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  CREATE_ORGANIZATION_SUCCESS: 'CREATE_ORGANIZATION_SUCCESS',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  DELETE_ORGANIZATION_SUCCESS: 'DELETE_ORGANIZATION_SUCCESS',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  UPDATE_ORGANIZATION_SUCCESS: 'UPDATE_ORGANIZATION_SUCCESS',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  GET_ORGANIZATION_SUCCESS: 'GET_ORGANIZATION_SUCCESS'
};
