export default {
  CREATE_ADMIN_USER: 'CREATE_ADMIN_USER',
  CREATE_ADMIN_USER_SUCCESS: 'CREATE_ADMIN_USER_SUCCESS',
  GET_ADMIN_USERS: 'GET_ADMIN_USERS',
  GET_ADMIN_USERS_SUCCESS: 'GET_ADMIN_USERS_SUCCESS',
  GET_ORGANIZATION_OPTIONS: 'GET_ORGANIZATION_OPTIONS',
  CHANGE_ORGANIZATION_LOADING_STATUS: 'CHANGE_ORGANIZATION_LOADING_STATUS',
  DELETE_ADMIN_USER: 'DELETE_ADMIN_USER',
  DELETE_ADMIN_USER_SUCCESS: 'DELETE_ADMIN_USER_SUCCESS'
};
