export default {
  CREATE_ADMIN_USER: 'CREATE_ADMIN_USER',
  CREATE_ADMIN_USER_SUCCESS: 'CREATE_ADMIN_USER_SUCCESS',
  GET_ADMIN_USERS: 'GET_ADMIN_USERS',
  GET_ADMIN_USERS_SUCCESS: 'GET_ADMIN_USERS_SUCCESS',
};
