export default {
  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
  CLOSE_SUCCESS_MESSAGE: 'HIDE_SUCCESS_MESSAGE',
  SHOW_ERROR_ALERT: 'SHOW_ERROR_ALERT',
  CLOSE_ERROR_ALERT: 'HIDE_ERROR_ALERT',
  SHOW_DELETE_MODAL: 'SHOW_DELETE_MODAL',
  CLOSE_DELETE_MODAL: 'CLOSE_DELETE_MODAL',
}
