export default {
  SHOW_SUCCESS_MESSAGE: 'SHOW_SUCCESS_MESSAGE',
  CLOSE_SUCCESS_MESSAGE: 'HIDE_SUCCESS_MESSAGE',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
  CLOSE_ERROR_MESSAGE: 'HIDE_ERROR_MESSAGE',
}
